sudo: false
language: python
python:
  - 2.7
env:
  - FLASK=0.11.1
install:
  - pip install Flask==$FLASK
  - pip install -r requirements.txt
script:
  - python runserver.py -m -d -u test -p test -a test -l "Boulder CO" -st 5 -ts
